-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-04-26 15:36:29 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

--student id: 30734819
--student name: Marcus Lim 

set echo on
SPOOL ad_schema_output.txt

DROP TABLE clinic CASCADE CONSTRAINTS;

DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE pet CASCADE CONSTRAINTS;

DROP TABLE pet_type CASCADE CONSTRAINTS;

DROP TABLE prescription CASCADE CONSTRAINTS;

DROP TABLE rove CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE specialisation CASCADE CONSTRAINTS;

DROP TABLE vet CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

DROP TABLE visit_service CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE clinic (
    clinic_id       NUMBER(5) NOT NULL,
    clinic_name     VARCHAR2(50) NOT NULL,
    clinic_address  VARCHAR2(50) NOT NULL,
    clinic_phone    CHAR(10) NOT NULL
);

COMMENT ON COLUMN clinic.clinic_id IS
    'clinic id';

COMMENT ON COLUMN clinic.clinic_name IS
    'clinic name ';

COMMENT ON COLUMN clinic.clinic_address IS
    'clinic address';

COMMENT ON COLUMN clinic.clinic_phone IS
    'clinic phone number';

ALTER TABLE clinic ADD CONSTRAINT clinic_pk PRIMARY KEY ( clinic_id );

CREATE TABLE drug (
    drug_id             NUMBER(5) NOT NULL,
    drug_name           VARCHAR2(50) NOT NULL,
    drug_usage_guide    VARCHAR2(100) NOT NULL,
    drug_standard_cost  NUMBER(6, 2) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'drug id';

COMMENT ON COLUMN drug.drug_name IS
    'drug name';

COMMENT ON COLUMN drug.drug_usage_guide IS
    'drug usage guide';

COMMENT ON COLUMN drug.drug_standard_cost IS
    'drug standard cost';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE owner (
    owner_id           NUMBER(6) NOT NULL,
    owner_givname      VARCHAR2(15) NOT NULL,
    owner_famname      VARCHAR2(15) NOT NULL,
    owner_addstreet    VARCHAR2(50) NOT NULL,
    owner_addtown      VARCHAR2(20) NOT NULL,
    owner_addpostcode  CHAR(4) NOT NULL,
    owner_phone        CHAR(10) NOT NULL,
    vet_id             NUMBER(6) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'owner id';

COMMENT ON COLUMN owner.owner_givname IS
    'owner given name';

COMMENT ON COLUMN owner.owner_famname IS
    'owner family name';

COMMENT ON COLUMN owner.owner_addstreet IS
    'owner street address';

COMMENT ON COLUMN owner.owner_addtown IS
    'owner town address';

COMMENT ON COLUMN owner.owner_addpostcode IS
    'owner address postcode';

COMMENT ON COLUMN owner.owner_phone IS
    'owner phone number';

COMMENT ON COLUMN owner.vet_id IS
    'vet id';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE pet (
    pet_id         NUMBER(6) NOT NULL,
    pet_gender     VARCHAR2(6) NOT NULL,
    pet_name       VARCHAR2(15) NOT NULL,
    pet_bdate      DATE NOT NULL,
    pet_deceased   CHAR(1) NOT NULL,
    pet_type_code  CHAR(5) NOT NULL,
    owner_id       NUMBER(6) NOT NULL
);

ALTER TABLE pet
    ADD CONSTRAINT chk_pet_deceased CHECK ( pet_deceased IN ( 'N', 'Y' ) );

COMMENT ON COLUMN pet.pet_id IS
    'pet id';

COMMENT ON COLUMN pet.pet_gender IS
    'pet gender';

COMMENT ON COLUMN pet.pet_name IS
    'pet name';

COMMENT ON COLUMN pet.pet_bdate IS
    'pet birthdate';

COMMENT ON COLUMN pet.pet_deceased IS
    'pet deceased status';

COMMENT ON COLUMN pet.pet_type_code IS
    'pet type code';

COMMENT ON COLUMN pet.owner_id IS
    'owner id';

ALTER TABLE pet ADD CONSTRAINT pet_pk PRIMARY KEY ( pet_id );

CREATE TABLE pet_type (
    pet_type_code  CHAR(5) NOT NULL,
    pet_type_name  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN pet_type.pet_type_code IS
    'pet type code';

COMMENT ON COLUMN pet_type.pet_type_name IS
    'pet type name';

ALTER TABLE pet_type ADD CONSTRAINT pet_type_pk PRIMARY KEY ( pet_type_code );

CREATE TABLE prescription (
    visit_id              NUMBER(10) NOT NULL,
    drug_id               NUMBER(5) NOT NULL,
    pres_drug_dose        VARCHAR2(50) NOT NULL,
    pres_drug_admin_freq  VARCHAR2(50) NOT NULL,
    pres_drug_qty         NUMBER(3) NOT NULL,
    pres_drug_cost        NUMBER(7, 2) NOT NULL
);

COMMENT ON COLUMN prescription.visit_id IS
    'visit id (surrogate PK)';

COMMENT ON COLUMN prescription.drug_id IS
    'drug id';

COMMENT ON COLUMN prescription.pres_drug_dose IS
    'prescribed drug dose';

COMMENT ON COLUMN prescription.pres_drug_admin_freq IS
    'prescribed drug administration frequency';

COMMENT ON COLUMN prescription.pres_drug_qty IS
    'prescribed drug quantity';

COMMENT ON COLUMN prescription.pres_drug_cost IS
    'prescribed drug cost';

ALTER TABLE prescription ADD CONSTRAINT prescription_pk PRIMARY KEY ( drug_id,
                                                                      visit_id );

CREATE TABLE rove (
    vet_id      NUMBER(6) NOT NULL,
    clinic_id   NUMBER(5) NOT NULL,
    rove_count  NUMBER(5)
);

COMMENT ON COLUMN rove.vet_id IS
    'vet id';

COMMENT ON COLUMN rove.clinic_id IS
    'clinic id';

COMMENT ON COLUMN rove.rove_count IS
    'number of times a specialised vet serviced in a clinic, which is not their home clinic';

ALTER TABLE rove ADD CONSTRAINT roving_pk PRIMARY KEY ( vet_id,
                                                        clinic_id );

CREATE TABLE service (
    service_code           CHAR(5) NOT NULL,
    service_desc           VARCHAR2(150) NOT NULL,
    service_standard_cost  NUMBER(6, 2) NOT NULL
);

COMMENT ON COLUMN service.service_code IS
    'service code';

COMMENT ON COLUMN service.service_desc IS
    'service description';

COMMENT ON COLUMN service.service_standard_cost IS
    'service standard cost';

ALTER TABLE service ADD CONSTRAINT service_pk PRIMARY KEY ( service_code );

CREATE TABLE specialisation (
    spec_code  CHAR(5) NOT NULL,
    spec_name  VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN specialisation.spec_code IS
    'area of specialisation code ';

COMMENT ON COLUMN specialisation.spec_name IS
    'name of the area of specialisation';

ALTER TABLE specialisation ADD CONSTRAINT specialisation_pk PRIMARY KEY ( spec_code );

CREATE TABLE vet (
    vet_id          NUMBER(6) NOT NULL,
    vet_givname     VARCHAR2(15) NOT NULL,
    vet_famname     VARCHAR2(15),
    vet_phone       CHAR(10) NOT NULL,
    vet_employdate  DATE NOT NULL,
    clinic_id       NUMBER(5) NOT NULL,
    spec_code       CHAR(5)
);

COMMENT ON COLUMN vet.vet_id IS
    'vet id';

COMMENT ON COLUMN vet.vet_givname IS
    'vet given name';

COMMENT ON COLUMN vet.vet_famname IS
    'vet family name';

COMMENT ON COLUMN vet.vet_phone IS
    'vet phone number';

COMMENT ON COLUMN vet.vet_employdate IS
    'vet''s first employed date';

COMMENT ON COLUMN vet.clinic_id IS
    'clinic id';

COMMENT ON COLUMN vet.spec_code IS
    'area of specialisation code ';

ALTER TABLE vet ADD CONSTRAINT vet_pk PRIMARY KEY ( vet_id );

CREATE TABLE visit (
    visit_id         NUMBER(10) NOT NULL,
    visit_datetime   DATE NOT NULL,
    pet_id           NUMBER(6) NOT NULL,
    visit_duration   NUMBER(4) NOT NULL,
    visit_notes      VARCHAR2(100),
    visit_totalcost  NUMBER(8, 2) NOT NULL,
    visit_paidby     CHAR(4) NOT NULL,
    vet_id           NUMBER(6) NOT NULL,
    clinic_id        NUMBER(5) NOT NULL,
    visit_id1        NUMBER(10) NOT NULL
);

ALTER TABLE visit
    ADD CONSTRAINT chk_visit_paidby CHECK ( visit_paidby IN ( 'CASH', 'EPT' ) );

COMMENT ON COLUMN visit.visit_id IS
    'visit id (surrogate PK)';

COMMENT ON COLUMN visit.visit_datetime IS
    'date and time of visit';

COMMENT ON COLUMN visit.pet_id IS
    'pet id';

COMMENT ON COLUMN visit.visit_duration IS
    'length/duration of the visit';

COMMENT ON COLUMN visit.visit_notes IS
    'notes made in that visit';

COMMENT ON COLUMN visit.visit_totalcost IS
    'total cost of the visit, including service cost and drug cost';

COMMENT ON COLUMN visit.visit_paidby IS
    'payment method of that visit';

COMMENT ON COLUMN visit.vet_id IS
    'vet id';

COMMENT ON COLUMN visit.clinic_id IS
    'clinic id';

COMMENT ON COLUMN visit.visit_id1 IS
    'visit id (surrogate PK)';

CREATE UNIQUE INDEX visit__idx ON
    visit (
        pet_id
    ASC );

ALTER TABLE visit ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_id );

ALTER TABLE visit ADD CONSTRAINT visit_nk UNIQUE ( visit_datetime,
                                                   pet_id );

CREATE TABLE visit_service (
    visit_id            NUMBER(10) NOT NULL,
    service_code        CHAR(5) NOT NULL,
    visit_service_cost  NUMBER(8, 2) NOT NULL
);

COMMENT ON COLUMN visit_service.visit_id IS
    'visit id (surrogate PK)';

COMMENT ON COLUMN visit_service.service_code IS
    'service code';

COMMENT ON COLUMN visit_service.visit_service_cost IS
    'cost of service in that visit';

ALTER TABLE visit_service ADD CONSTRAINT visit_service_pk PRIMARY KEY ( service_code,
                                                                        visit_id );

ALTER TABLE rove
    ADD CONSTRAINT clinic_roving FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE vet
    ADD CONSTRAINT clinic_vet FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE visit
    ADD CONSTRAINT clinic_visit FOREIGN KEY ( vet_id,
                                              clinic_id )
        REFERENCES rove ( vet_id,
                          clinic_id );

ALTER TABLE prescription
    ADD CONSTRAINT drug_prescription FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE pet
    ADD CONSTRAINT owner_pet FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE visit
    ADD CONSTRAINT pet_visit FOREIGN KEY ( pet_id )
        REFERENCES pet ( pet_id );

ALTER TABLE pet
    ADD CONSTRAINT pettype_pet FOREIGN KEY ( pet_type_code )
        REFERENCES pet_type ( pet_type_code );

ALTER TABLE visit_service
    ADD CONSTRAINT service_visitservice FOREIGN KEY ( service_code )
        REFERENCES service ( service_code );

ALTER TABLE vet
    ADD CONSTRAINT specialisation_vet FOREIGN KEY ( spec_code )
        REFERENCES specialisation ( spec_code );

ALTER TABLE owner
    ADD CONSTRAINT vet_owner FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE rove
    ADD CONSTRAINT vet_roving FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE prescription
    ADD CONSTRAINT visit_prescription FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );

ALTER TABLE visit
    ADD CONSTRAINT visit_subsequentvisit FOREIGN KEY ( visit_id1 )
        REFERENCES visit ( visit_id );

ALTER TABLE visit_service
    ADD CONSTRAINT visit_visitservice FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             1
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off